# syntax=docker/dockerfile:1
   
FROM alpine:3

ENV LANG C.UTF-8
ENV TZ="US/Pacific"

# Someone else's setup
# https://gist.github.com/mikilian/d92f9cd22803b9c61725c86391618615
# You got to remove all the extra stuff manually.
# https://stackoverflow.com/questions/54131066/lightweight-gcc-for-alpine
# Clang 16 has the tools and it takes 400-600 MB
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
         clang \
         clang-dev \
         clang-libs \
         clang-extra-tools \
         g++ \
         py3-pexpect \
         gmock \
         gtest \
         gtest-dev \
         git \
         ca-certificates \
         tzdata

# https://wiki.alpinelinux.org/wiki/Setting_the_timezone
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apk del tzdata


# RUN apt update \
# && apt install -y --no-install-recommends build-essential clang clang-format clang-tidy python3-pexpect libgmock-dev libgtest-dev git ca-certificates \
# && apt clean all \
# && apt autoremove

# https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user
RUN adduser --shell /usr/bin/bash --disabled-password --gecos "Tuffy Titan" tuffy
# RUN useradd --comment "Tuffy Titan" --create-home --shell /bin/bash tuffy
