# syntax=docker/dockerfile:1
   
FROM alpine:3

ENV LANG C.UTF-8
ENV TZ=PDT

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
         clang14 \
         clang14-dev \
         clang14-libs \
         py3-pexpect \
         gmock \
         gtest \
         gtest-dev \
         git \
         ca-certificates \
         tzdata

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apk del tzdata


# RUN apt update \
# && apt install -y --no-install-recommends build-essential clang clang-format clang-tidy python3-pexpect libgmock-dev libgtest-dev git ca-certificates \
# && apt clean all \
# && apt autoremove

# https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user
RUN adduser --shell /usr/bin/bash --disabled-password --gecos "Tuffy Titan" tuffy
# RUN useradd --comment "Tuffy Titan" --create-home --shell /bin/bash tuffy
