# syntax=docker/dockerfile:1
   
FROM ubuntu:jammy

ENV LANG C.UTF-8
ENV TZ=PDT
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update \
&& apt install -y --no-install-recommends build-essential clang clang-format clang-tidy python3-pexpect libgmock-dev libgtest-dev git ca-certificates \
&& apt clean all \
&& apt autoremove

RUN adduser --shell /usr/bin/bash --disabled-password --gecos "Tuffy Titan" tuffy
